# Generated by Django 5.1 on 2024-08-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_tournament_status_tournament_is_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertournament',
            unique_together={('user', 'tournament')},
        ),
    ]
