# Generated by Django 5.0.6 on 2024-07-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_singlematch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlematch',
            name='type',
        ),
        migrations.AlterField(
            model_name='singlematch',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
