# Generated by Django 5.0.6 on 2024-07-29 19:00

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_tournament_score_singlematch_matchtournament_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchtournament',
            name='match',
        ),
        migrations.RemoveField(
            model_name='matchtournament',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='score',
            name='user',
        ),
        migrations.RemoveField(
            model_name='singlematch',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='singlematch',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='tournamentscore',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='usertournament',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournamentscore',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usertournament',
            name='user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='dahmad',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.DeleteModel(
            name='FriendShip',
        ),
        migrations.DeleteModel(
            name='matchTournament',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='singleMatch',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
        migrations.DeleteModel(
            name='tournamentScore',
        ),
        migrations.DeleteModel(
            name='userTournament',
        ),
    ]
